import "@/Sass/index.scss";
import Footer from "@/Components/Footer";
import Header from "@/Components/Header";
import StoreProvider from "@/Redux/StoreProvider";

export const metadata = {
	title: "School Management",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<StoreProvider>
					<Header />
					<main>{children}</main>
					<Footer />
				</StoreProvider>
			</body>
		</html>
	);
}
